name: Build Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0
      - name: Build and publish OCI image
        run: |
          pack build jeroenkolk/my-helloworld-packer/tst:latest \
            -B paketobuildpacks/builder-jammy-base \
            --env "BP_WEB_SERVER=nginx" \
            --env "BP_WEB_SERVER_ROOT=dist" \
            --env "BP_WEB_SERVER_ENABLE_PUSH_STATE=true" \
            --env "NODE_ENV=production" \
            --publish
